project:
  type: website
  output-dir: docs

website:
  title: "Sam English"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd
      - text: "Data Viz"
        menu: 
          - text: "Chocolate Ratings vs. Cocoa Percentage"
            href: ChocolateRatings.html
          - text: "World Cup Goals Over Time"
            href: WorldCup.html
          - text: "Netflix Title Analysis"
            href: "MiniProject2.html"
          - text: "Generational Marijuana Use Statistical Analysis"
            href: "MiniProject3.html"
          - text: "SQL Analysis of WAI Data for Auditory Research"
            href: "MiniProject4.html"
          - text: "Project Presentation"
            href: "Presentation.html"
            

         
         

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

