project:
  type: website
  output-dir: docs

website:
  title: "Sam English"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd
      - text: "Data Viz"
        menu: 
         - text: "Chocolate Ratings"
           href: ChocolateRatings.html
         - text: "World Cup"
           href: WorldCup.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

